### PR TITLE
Revamp docs site

### LINKED ISSUE #82: Fix compile warning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
See https://github.com/micrometer-metrics/micrometer-docs/commit/47321f0ca9dcd21884916a9e89c49599943bf132#r32759033

### LINKED ISSUE #88: Navigation bar toggler doesn't work
IIRC it was working before but I'm not 100% sure.

### LINKED ISSUE #108: Reconsider hard-coded script tags
When the script tags reverted in #104 were removed, it broke the sandwich menu on the mobile site. We should still understand why that is and what is the ideal state.

_Originally posted by @shakuzen in https://github.com/micrometer-metrics/micrometer-docs/pull/104#issuecomment-555839472_

### PR DESCRIPTION
**Pull request by shakuzen**
Gets rid of dependencies we did not need.
Replaces hard-coded javascript imports with react-bootstrap. The imports weren't loading in Chrome for me anyways.
Fixes the navbar collapse not working in Chrome.
Fixes warnings in console during development time.
Updates dependencies (notably react 17).
I've tried to check that everything is working still.

Fixes #82
Fixes #108
Fixes #88

### CODE REVIEW

File: src/components/MyNavbar/index.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import React from 'react';
+import {Link} from 'react-router-dom';
+import logo from '../../img/logo.svg';
+import 'font-awesome/css/font-awesome.min.css';
+import './style.css';
+import { Nav, Navbar } from "react-bootstrap";
+
+export default function MyNavbar() {
```
Comment (shakuzen) [inline src/components/MyNavbar/index.js:8]: Renamed to `MyNavbar` to avoid the name clash with react-bootstrap's `Navbar` type.
